spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
    driver-class-name : com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    application:
      name: ratingService
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql : true
server:
  port: 8082
  servlet:
    context-path: /ratingService