spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
    driver-class-name : com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: RATING-SERVICE
  config: # from here this is for cloud config where fetching the configuration from the GIT
    import: optional:configserver:http://localhost:8086
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql : true
server:
  port: 8085
  servlet:
    context-path: /ratingService

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka